version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset_exp_lc:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_exp_lc.py
        --output output/dataset_exp_lc.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_exp_lc.csv

  generate_dataset_lc_gp:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_lc_gp_list.py
        --output output/dataset_lc_gp_list.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_lc_gp_list.csv

  generate_dataset_comparator_large:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_comparator_large.py
        --output output/dataset_comparator_large.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_comparator_large.csv

  # generate_dataset_comparator_filtered_gp:
  #   run: r:latest analysis/dm01_filter_gp_without_lc_dx.R      
  #   needs: [generate_dataset_comparator_large, generate_dataset_lc_gp]
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/dataset_comparator_filtered_gp.csv


  # match_comparators:
  #   run:
  #     python:latest python analysis/match.py
  #   needs: [generate_dataset_comparator_filtered_gp, generate_dataset_exp_lc]
  #   outputs: 
  #     highly_sensitive:
  #       matched_cases: output/matched_cases.csv
  #       matched_matches: output/matched_matches.csv
  #       matched_all: output/matched_combined.csv
  #     moderately_sensitive: 
  #       matching_report: output/matching_report.txt