version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition.py
        --output output/dataset.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv


  generate_longcovid:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_longcovid.py
        --output output/dataset_longcovid.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_longcovid.csv