version: '3.0'

expectations:
  population_size: 500

actions:

  generate_long_covid_exposure_dataset:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_unmatched_exp_lc.py
        --output output/dataset_exp_lc_unmatched.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/dataset_exp_lc_unmatched.csv.gz

  check_stp_regions:
    needs: [generate_long_covid_exposure_dataset]
    run: r:latest analysis/dm00_check_stp_regions.R
    outputs:
      moderately_sensitive: 
        stp_region: output/stp_regions_counts.csv.gz

  generate_list_gp_use_long_covid_dx:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_lc_gp_list.py
        --output output/dataset_lc_gp_list.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_lc_gp_list.csv

  generate_dataset_comparator_exclude_gp_no_long_covid:
    needs: [generate_list_gp_use_long_covid_dx]
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_unmatched_comparator.py
        --output output/dataset_comparator_unmatched.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/dataset_comparator_unmatched.csv.gz

  test_matching:
    run:
      python:latest python analysis/match_test.py
    needs: [generate_dataset_comparator_exclude_gp_no_long_covid, generate_long_covid_exposure_dataset]
    outputs: 
      highly_sensitive:
        matched_cases: output/matched_cases_stp.csv.gz
        matched_matches: output/matched_matches_stp.csv.gz
        matched_all: output/matched_combined_stp.csv.gz
      moderately_sensitive: 
        matching_report: output/matching_report_stp.txt


  # split_unmatched_data_by_stp_regions:
  #   needs: [generate_long_covid_exposure_dataset, generate_dataset_comparator_exclude_gp_no_long_covid]
  #   run: r:latest analysis/dm00_split_stp_for_matching.R
  #   outputs: 
  #     moderately_sensitive: 
  #       stp_exp_table: output/exp_stp_names_numbers.csv
  #       stp_com_table: output/com_stp_names_numbers.csv
  #     highly_sensitive: 
  #       # exp_stp_: output/exp_stp_.csv
  #       exp_stp_5: output/exp_stp_05.csv
  #       exp_stp_24: output/exp_stp_24.csv
  #       exp_stp_26: output/exp_stp_26.csv
  #       exp_stp_23: output/exp_stp_23.csv
  #       exp_stp_6: output/exp_stp_06.csv
  #       exp_stp_13: output/exp_stp_13.csv
  #       exp_stp_49: output/exp_stp_49.csv
  #       exp_stp_15: output/exp_stp_15.csv
  #       exp_stp_41: output/exp_stp_41.csv
  #       exp_stp_9: output/exp_stp_09.csv
  #       exp_stp_17: output/exp_stp_17.csv
  #       exp_stp_25: output/exp_stp_25.csv
  #       exp_stp_16: output/exp_stp_16.csv
  #       exp_stp_7: output/exp_stp_07.csv
  #       exp_stp_42: output/exp_stp_42.csv
  #       exp_stp_21: output/exp_stp_21.csv
  #       exp_stp_40: output/exp_stp_40.csv
  #       exp_stp_27: output/exp_stp_27.csv
  #       exp_stp_14: output/exp_stp_14.csv
  #       exp_stp_20: output/exp_stp_20.csv
  #       exp_stp_29: output/exp_stp_29.csv
  #       exp_stp_43: output/exp_stp_43.csv
  #       exp_stp_8: output/exp_stp_08.csv
  #       exp_stp_37: output/exp_stp_37.csv
  #       exp_stp_22: output/exp_stp_22.csv
  #       exp_stp_12: output/exp_stp_12.csv
  #       exp_stp_33: output/exp_stp_33.csv
  #       exp_stp_35: output/exp_stp_35.csv
  #       exp_stp_36: output/exp_stp_36.csv
  #       exp_stp_10: output/exp_stp_10.csv
  #       exp_stp_44: output/exp_stp_44.csv
  #       # com_stp_: output/com_stp_.csv
  #       com_stp_5: output/com_stp_05.csv
  #       com_stp_24: output/com_stp_24.csv
  #       com_stp_26: output/com_stp_26.csv
  #       com_stp_23: output/com_stp_23.csv
  #       com_stp_6: output/com_stp_06.csv
  #       com_stp_13: output/com_stp_13.csv
  #       com_stp_49: output/com_stp_49.csv
  #       com_stp_15: output/com_stp_15.csv
  #       com_stp_41: output/com_stp_41.csv
  #       com_stp_9: output/com_stp_09.csv
  #       com_stp_17: output/com_stp_17.csv
  #       com_stp_25: output/com_stp_25.csv
  #       com_stp_16: output/com_stp_16.csv
  #       com_stp_7: output/com_stp_07.csv
  #       com_stp_42: output/com_stp_42.csv
  #       com_stp_21: output/com_stp_21.csv
  #       com_stp_40: output/com_stp_40.csv
  #       com_stp_27: output/com_stp_27.csv
  #       com_stp_14: output/com_stp_14.csv
  #       com_stp_20: output/com_stp_20.csv
  #       com_stp_29: output/com_stp_29.csv
  #       com_stp_43: output/com_stp_43.csv
  #       com_stp_8: output/com_stp_08.csv
  #       com_stp_37: output/com_stp_37.csv
  #       com_stp_22: output/com_stp_22.csv
  #       com_stp_12: output/com_stp_12.csv
  #       com_stp_33: output/com_stp_33.csv
  #       com_stp_35: output/com_stp_35.csv
  #       com_stp_36: output/com_stp_36.csv
  #       com_stp_10: output/com_stp_10.csv
  #       com_stp_44: output/com_stp_44.csv

  # match_comparators_05:
  #   run:
  #     python:latest python analysis/matching_05.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs: 
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_05.csv
  #       matched_matches: output/matched_matches_stp_05.csv
  #       matched_all: output/matched_combined_stp_05.csv
  #     moderately_sensitive: 
  #       matching_report: output/matching_report_stp_05.txt

  #   match_comparators_24:
  #   run:
  #     python:latest python analysis/matching_24.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_24.csv
  #       matched_matches: output/matched_matches_stp_24.csv
  #       matched_all: output/matched_combined_stp_24.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_24.txt


  # match_comparators_26:
  #   run:
  #     python:latest python analysis/matching_26.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_26.csv
  #       matched_matches: output/matched_matches_stp_26.csv
  #       matched_all: output/matched_combined_stp_26.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_26.txt


  # match_comparators_23:
  #   run:
  #     python:latest python analysis/matching_23.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_23.csv
  #       matched_matches: output/matched_matches_stp_23.csv
  #       matched_all: output/matched_combined_stp_23.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_23.txt


  # match_comparators_6:
  #   run:
  #     python:latest python analysis/matching_6.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_6.csv
  #       matched_matches: output/matched_matches_stp_6.csv
  #       matched_all: output/matched_combined_stp_6.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_6.txt


  # match_comparators_13:
  #   run:
  #     python:latest python analysis/matching_13.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_13.csv
  #       matched_matches: output/matched_matches_stp_13.csv
  #       matched_all: output/matched_combined_stp_13.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_13.txt


  # match_comparators_49:
  #   run:
  #     python:latest python analysis/matching_49.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_49.csv
  #       matched_matches: output/matched_matches_stp_49.csv
  #       matched_all: output/matched_combined_stp_49.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_49.txt


  # match_comparators_15:
  #   run:
  #     python:latest python analysis/matching_15.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_15.csv
  #       matched_matches: output/matched_matches_stp_15.csv
  #       matched_all: output/matched_combined_stp_15.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_15.txt


  # match_comparators_41:
  #   run:
  #     python:latest python analysis/matching_41.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_41.csv
  #       matched_matches: output/matched_matches_stp_41.csv
  #       matched_all: output/matched_combined_stp_41.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_41.txt


  # match_comparators_09:
  #   run:
  #     python:latest python analysis/matching_09.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_09.csv
  #       matched_matches: output/matched_matches_stp_09.csv
  #       matched_all: output/matched_combined_stp_09.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_09.txt


  # match_comparators_17:
  #   run:
  #     python:latest python analysis/matching_17.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_17.csv
  #       matched_matches: output/matched_matches_stp_17.csv
  #       matched_all: output/matched_combined_stp_17.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_17.txt


  # match_comparators_25:
  #   run:
  #     python:latest python analysis/matching_25.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_25.csv
  #       matched_matches: output/matched_matches_stp_25.csv
  #       matched_all: output/matched_combined_stp_25.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_25.txt


  # match_comparators_16:
  #   run:
  #     python:latest python analysis/matching_16.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_16.csv
  #       matched_matches: output/matched_matches_stp_16.csv
  #       matched_all: output/matched_combined_stp_16.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_16.txt


  # match_comparators_07:
  #   run:
  #     python:latest python analysis/matching_07.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_07.csv
  #       matched_matches: output/matched_matches_stp_07.csv
  #       matched_all: output/matched_combined_stp_07.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_07.txt


  # match_comparators_42:
  #   run:
  #     python:latest python analysis/matching_42.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_42.csv
  #       matched_matches: output/matched_matches_stp_42.csv
  #       matched_all: output/matched_combined_stp_42.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_42.txt


  # match_comparators_21:
  #   run:
  #     python:latest python analysis/matching_21.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_21.csv
  #       matched_matches: output/matched_matches_stp_21.csv
  #       matched_all: output/matched_combined_stp_21.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_21.txt


  # match_comparators_40:
  #   run:
  #     python:latest python analysis/matching_40.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_40.csv
  #       matched_matches: output/matched_matches_stp_40.csv
  #       matched_all: output/matched_combined_stp_40.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_40.txt


  # match_comparators_27:
  #   run:
  #     python:latest python analysis/matching_27.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_27.csv
  #       matched_matches: output/matched_matches_stp_27.csv
  #       matched_all: output/matched_combined_stp_27.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_27.txt


  # match_comparators_14:
  #   run:
  #     python:latest python analysis/matching_14.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_14.csv
  #       matched_matches: output/matched_matches_stp_14.csv
  #       matched_all: output/matched_combined_stp_14.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_14.txt


  # match_comparators_20:
  #   run:
  #     python:latest python analysis/matching_20.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_20.csv
  #       matched_matches: output/matched_matches_stp_20.csv
  #       matched_all: output/matched_combined_stp_20.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_20.txt


  # match_comparators_29:
  #   run:
  #     python:latest python analysis/matching_29.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_29.csv
  #       matched_matches: output/matched_matches_stp_29.csv
  #       matched_all: output/matched_combined_stp_29.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_29.txt


  # match_comparators_43:
  #   run:
  #     python:latest python analysis/matching_43.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_43.csv
  #       matched_matches: output/matched_matches_stp_43.csv
  #       matched_all: output/matched_combined_stp_43.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_43.txt


  # match_comparators_08:
  #   run:
  #     python:latest python analysis/matching_08.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_08.csv
  #       matched_matches: output/matched_matches_stp_08.csv
  #       matched_all: output/matched_combined_stp_08.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_08.txt


  # match_comparators_37:
  #   run:
  #     python:latest python analysis/matching_37.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_37.csv
  #       matched_matches: output/matched_matches_stp_37.csv
  #       matched_all: output/matched_combined_stp_37.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_37.txt


  # match_comparators_22:
  #   run:
  #     python:latest python analysis/matching_22.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_22.csv
  #       matched_matches: output/matched_matches_stp_22.csv
  #       matched_all: output/matched_combined_stp_22.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_22.txt


  # match_comparators_12:
  #   run:
  #     python:latest python analysis/matching_12.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_12.csv
  #       matched_matches: output/matched_matches_stp_12.csv
  #       matched_all: output/matched_combined_stp_12.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_12.txt


  # match_comparators_33:
  #   run:
  #     python:latest python analysis/matching_33.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_33.csv
  #       matched_matches: output/matched_matches_stp_33.csv
  #       matched_all: output/matched_combined_stp_33.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_33.txt


  # match_comparators_35:
  #   run:
  #     python:latest python analysis/matching_35.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_35.csv
  #       matched_matches: output/matched_matches_stp_35.csv
  #       matched_all: output/matched_combined_stp_35.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_35.txt


  # match_comparators_36:
  #   run:
  #     python:latest python analysis/matching_36.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_36.csv
  #       matched_matches: output/matched_matches_stp_36.csv
  #       matched_all: output/matched_combined_stp_36.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_36.txt


  # match_comparators_10:
  #   run:
  #     python:latest python analysis/matching_10.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_10.csv
  #       matched_matches: output/matched_matches_stp_10.csv
  #       matched_all: output/matched_combined_stp_10.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_10.txt


  # match_comparators_44:
  #   run:
  #     python:latest python analysis/matching_44.py
  #   needs: [split_unmatched_data_by_stp_regions]
  #   outputs:
  #     highly_sensitive:
  #       matched_cases: output/matched_cases_stp_44.csv
  #       matched_matches: output/matched_matches_stp_44.csv
  #       matched_all: output/matched_combined_stp_44.csv
  #     moderately_sensitive:
  #       matching_report: output/matching_report_stp_44.txt
