version: '3.0'

expectations:
  population_size: 5000

actions:
# Contemporary comparison data management:
# # Before matching data management:
  generate_long_covid_exposure_dataset:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_unmatched_exp_lc.py
        --output output/dataset_exp_lc_unmatched.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_exp_lc_unmatched.csv

  generate_list_gp_use_long_covid_dx:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_lc_gp_list.py
        --output output/dataset_lc_gp_list.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_lc_gp_list.csv

  generate_dataset_comparator_exclude_gp_no_long_covid:
    needs: [generate_list_gp_use_long_covid_dx]
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_unmatched_comparator.py
        --output output/dataset_comparator_unmatched.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_comparator_unmatched.csv
        
# # # QC step:         
  qc_01examine_unmatched_data:
    needs: [generate_dataset_comparator_exclude_gp_no_long_covid, generate_long_covid_exposure_dataset]  
    run: 
      r:latest analysis/qc01_unmatched_control.R
    outputs:
      moderately_sensitive:
        cohort: output/qc01_check_unmatched.csv
        
# # OS matching
  test_matching:
    run:
      python:latest python analysis/match_test.py
    needs: [generate_dataset_comparator_exclude_gp_no_long_covid, generate_long_covid_exposure_dataset]
    outputs: 
      highly_sensitive:
        matched_cases: output/matched_cases_stp.csv
        matched_matches: output/matched_matches_stp.csv
        matched_all: output/matched_combined_stp.csv
      moderately_sensitive: 
        matching_report: output/matching_report_stp.txt
# # After matching data management
  import_matched_exposure:
    run: >
       databuilder:v0
        generate-dataset analysis/dataset_definition_matched_cases.py
        --output output/matched_cases_with_ehr.csv.gz
    needs: [test_matching]
    outputs: 
      highly_sensitive:
        cohort: output/matched_cases_with_ehr.csv.gz

  import_matched_controls:
    run: >
       databuilder:v0
        generate-dataset analysis/dataset_definition_matched_control.py
        --output output/matched_control_with_ehr.csv.gz
    needs: [test_matching]
    outputs: 
      highly_sensitive:
        cohort: output/matched_control_with_ehr.csv.gz


  import_matched_exposure_drug_cost:
    run: >
       databuilder:v0
        generate-dataset analysis/dataset_definition_matched_cases_drug_costs.py
        --output output/matched_cases_with_drug_costs.csv.gz
    needs: [test_matching]
    outputs: 
      highly_sensitive:
        cohort: output/matched_cases_with_drug_costs.csv.gz

  import_matched_controls_drug_costs:
    run: >
       databuilder:v0
        generate-dataset analysis/dataset_definition_matched_control_drug_costs.py
        --output output/matched_control_with_drug_costs.csv.gz
    needs: [test_matching]
    outputs: 
      highly_sensitive:
        cohort: output/matched_control_with_drug_costs.csv.gz


# Historical comparison data management:
# # Before matching data management:
  generate_historical_exp_data:
    run: 
      databuilder:v0 generate-dataset analysis/dataset_definition_hx_unmatched_exp_lc.py
        --output output/hx_unmatched_exp.csv
    outputs:
      highly_sensitive:
        hx_cohort: output/hx_unmatched_exp.csv
  
  generate_historical_comp_data_exclude_gp_no_long_covid:
    needs: [generate_list_gp_use_long_covid_dx]
    run: 
      databuilder:v0 generate-dataset analysis/dataset_definition_hx_unmatched_com_no_lc.py
        --output output/hx_dataset_comp_unmatched.csv
    outputs:
      highly_sensitive:
        hx_cohort: output/hx_dataset_comp_unmatched.csv
        
# # # QC step:         
  qc_02examine_historical_unmatched_data:
    needs: [generate_historical_exp_data, generate_historical_comp_data_exclude_gp_no_long_covid]  
    run: 
      r:latest analysis/qc02_hx_unmatched_check.R
    outputs:
      moderately_sensitive:
        cohort: output/qc02_hx_check_unmatched.csv
        
# # OS matching
  historical_matching:
    run:
      python:latest python analysis/match_historical.py
    needs: [generate_historical_exp_data, generate_historical_comp_data_exclude_gp_no_long_covid]
    outputs: 
      highly_sensitive:
        matched_cases: output/matched_cases_historical.csv
        matched_matches: output/matched_matches_historical.csv
        matched_all: output/matched_combined_historical.csv
      moderately_sensitive: 
        matching_report: output/matching_report_historical.txt

# # After matching data management
  import_matched_historical_exposure:
    run: >
       databuilder:v0
        generate-dataset analysis/dataset_definition_hx_matched_exp_lc.py
        --output output/hx_matched_cases_with_ehr.csv.gz
    needs: [historical_matching]
    outputs: 
      highly_sensitive:
        cohort: output/hx_matched_cases_with_ehr.csv.gz

  import_matched_historical_controls:
    run: >
       databuilder:v0
        generate-dataset analysis/dataset_definition_hx_matched_comp.py
        --output output/hx_matched_control_with_ehr.csv.gz
    needs: [historical_matching]
    outputs: 
      highly_sensitive:
        cohort: output/hx_matched_control_with_ehr.csv.gz

# Reporting: demographic distribution 

# Contemporary comparison: 
  report01_matched_datasets:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st01_report_matched.R
    outputs: 
      moderately_sensitive: 
        matched_table: output/st01_matched_numbers_table.csv  # Table 1
        explore_fu_time: output/st01_matched_numbers_check_fu.csv # check the incorrect follow-up time
        explore_vax_fig: output/st1_exporing_vax_index_date.png # Check vax date
        missing_table: output/missing_distribution_table.csv # Missing pattern tab
        missing_pattern: output/missing_pattern_current.png # Missing patter plot


# Check follow-up time 
  qc_03_check_na:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/qc03_now_check_followup.R
    outputs: 
      moderately_sensitive: 
        check_na_in_data: output/st02_check_min.csv

# Contemporary comparison
# # Basic: non-cluster all analysis

  report_02_basic_model_output:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st02_01_00_model_curr_nb_reg.R
    outputs: 
      moderately_sensitive: 
        model_non_clustered_results: output/st_02_non_cluster_model.csv


# # Basic: non-cluster gp visits outcome anaylses

  report_02_basic_model_gp_output:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st02_01_06_y_gp_model_curr_nb_reg.R
    outputs: 
      moderately_sensitive: 
        model_non_clustered_results: output/st_02_0106_y_gp_no_cluster_model.csv

# # Basic: non-cluster hospital visits outcome anaylses

  report_02_basic_model_hos_output:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st02_01_07_y_hos_model_curr_nb_reg.R
    outputs: 
      moderately_sensitive: 
        model_non_clustered_results: output/st_02_0107_y_hos_no_cluster_model.csv


# # Basic: non-cluster A&E visits outcome anaylses

  report_02_basic_model_ane_output:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st02_01_08_y_ane_model_curr_nb_reg.R
    outputs: 
      moderately_sensitive: 
        model_non_clustered_results: output/st_02_0108_y_ae_no_cluster_model.csv

# # Basic: non-cluster outpatient clinic visits outcome anaylses

  report_02_basic_model_opa_output:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st02_01_09_y_opa_model_curr_nb_reg.R
    outputs: 
      moderately_sensitive: 
        model_non_clustered_results: output/st_02_0109_y_opa_no_cluster_model.csv

  qc_04_check_opa_distribution:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/qc04_check_opa_outcomes.R
    outputs: 
      moderately_sensitive: 
        opa_distribution_all: output/opa_outcome_distribution.csv

# # Basic: non-cluster sub-group analysis

  report_02_basic_model__subgroup:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st02_01_x_subgroups_model_curr_nb.R
    outputs: 
      moderately_sensitive: 
        model_non_clustered_subgroup_results: output/st_02_subgroup_by_cov.csv
        
        
# Two part hurdle model:
# # All healthcare utilisation 

  report_03_hurdle_01_all_visits:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st03_01_model_curr_nb_hurdel.R
    outputs: 
      moderately_sensitive: 
        hurdle_all_visits: output/st03_01_hurdle_all_visits.csv

# # GP utilisation  - hurdle

  report_03_hurdle_02_gp_visits:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st03_02_model06_gp_hurdel.R
    outputs: 
      moderately_sensitive: 
        hurdle_gp_visits: output/st03_02_hurdle_gp_visits.csv

# # Hospital admission - hurdle

  report_03_hurdle_03_hospital_admin:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st03_03_model07_hos_hurdel.R
    outputs: 
      moderately_sensitive: 
        hurdle_hospital_admin: output/st03_03_hurdle_hos_visits.csv
        
# # A&E visits - hurdle
        
  report_03_hurdle_04_ane_visits:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st03_04_model08_ane_hurdel.R
    outputs: 
      moderately_sensitive: 
        hurdle_ane_visits: output/st03_04_hurdle_ane_visits.csv

# Historical: data distribution
  report05_hx_matched_data_distribution:
    needs: [import_matched_historical_exposure, import_matched_historical_controls]
    run: 
      r:latest analysis/st05_report_matched_historical_records.R
    outputs: 
      moderately_sensitive: 
        historical_table_1: output/st05_hx_matched_numbers_table.csv
        crude_visits_distribution: output/st05_hx_crude_vistis_exp_time.csv

# # Historical: difference-in-difference model

  report_05_did_model:      
    needs: [import_matched_historical_exposure, import_matched_historical_controls]
    run: 
      r:latest analysis/st05_did_model.R
    outputs: 
      moderately_sensitive: 
        did_crude: output/st05_did_crude.png
        did_adj: output/st05_did_adj.png
        did_reg_predict: output/st05_did_reg.csv

# # # Advanced: cluster analysis
#   report_03_model_02_clustered_analysis:
#     needs: [import_matched_exposure, import_matched_controls]
#     run: 
#       r:latest analysis/st03_model_02_cluster_analysis.R
#     outputs: 
#       moderately_sensitive: 
#         # model_compares_poisson: output/st03_model_02_rm_models.csv.gz
#         gee_outputs: output/st03_model_02_gee_models.csv
        
        
#   report_03_hurdle_model:
#     needs: [import_matched_exposure, import_matched_controls]
#     run: 
#       r:latest analysis/st03_hurdle_model_rate_ratio.R
#     outputs: 
#       moderately_sensitive: 
#         model_selection: output/sup_st03_0_model_comparison.csv
#         hurdle_all: output/st_03_result_monthly_visit_hurdle.csv
        
#   report_03_1_hurdle_model_predict:
#     needs: [import_matched_exposure, import_matched_controls]
#     run: 
#       r:latest analysis/st03_hurdle_model_predict.R
#     outputs: 
#       moderately_sensitive: 
#         hurdle_all: output/st_03_result_cumulative_visit_hurdle.csv
#         hurdle_gp: output/st_03_gp_result_cumulative_visit_hurdle.csv
#         hurdle_hos: output/st_03_hos_result_cumulative_visit_hurdle.csv
#         hurdle_ae: output/st_03_ae_result_cumulative_visit_hurdle.csv
        
#   report_04_hurdle_model_plot:
#     needs: [report_03_1_hurdle_model_predict]
#     run: 
#       r:latest analysis/st04_plot_hurdle_visit.R
#     outputs: 
#       moderately_sensitive: 
#         crude: output/st_04_crude_healthcare_visit.png
#         partial: output/st_04_partial_adj_healthcare_visit.png
#         full: output/st_04_full_adj_healthcare_visit.png
  
#   report_03_2_hurdle_model_sugroup_predict:
#     needs: [import_matched_exposure, import_matched_controls]
#     run: 
#       r:latest analysis/st03_sub_hurdle_model_predict.R
#     outputs: 
#       moderately_sensitive: 
#         subgroup_hos_visit: output/st_03_subgroup_result_hos_cumulative_visit_hurdle.csv
        
#   report_03_3_twopart_model_predict:
#     needs: [import_matched_exposure, import_matched_controls]
#     run: 
#       r:latest analysis/st03_two_part_model.R
#     outputs: 
#       moderately_sensitive: 
#         total_costs: output/st_04_result_cumulative_cost_full_2pm.csv
        
#   report_03_4_twopart_model_subgroup_predict:
#     needs: [import_matched_exposure, import_matched_controls]
#     run: 
#       r:latest analysis/st03_twopart_sub_model.R
#     outputs: 
#       moderately_sensitive: 
#         sub_costs: output/st_04_result_sub_cumulative_cost_2pm.csv       

#   report_04_plot_twopart_costs:
#     needs: [report_03_3_twopart_model_predict]
#     run: 
#       r:latest analysis/st04_fig_plot_twopm_cost.R
#     outputs: 
#       moderately_sensitive: 
#         plot_total_costs: "output/st_fig_04_cumulative_costs.png"
        
# Supplementary materials

  report_sup_exploring_outcome_dist:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st_sup_01_data_exploration.R
    outputs: 
      moderately_sensitive: 
        zero_percent_fig: output/st_sup_1_5_explore_zero_percentage.png
        monthly_oucome_tb: output/st_sup_1_5_monthly_outcome_distribution.csv
        visit_explore: output/st_sup_1_5_cat_visits_summary.csv
        
  report_sup_model_selection:
    needs: [import_matched_exposure, import_matched_controls]
    run: 
      r:latest analysis/st_sup_01_model_selection.R
    outputs: 
      moderately_sensitive: 
        model_01_poisson: output/st_sup_model_selection.csv