version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset_exp_lc:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_exp_lc.py
        --output output/dataset_exp_lc.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_exp_lc.csv

  generate_dataset_lc_gp:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_lc_gp_list.py
        --output output/dataset_lc_gp_list.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_lc_gp_list.csv


  generate_dataset_comparator_large:
    run: 
      databuilder:v0 generate-dataset
        analysis/dataset_definition_comparator_large.py
        --output output/dataset_comparator_large.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_comparator_large.csv
