version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: 
      databuilder:v0 generate_dataset
        --dataset-definition analysis/dataset_definition.py
        --dummy-data-file dummy_data.csv
        --output output/dataset.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv