# Load all packages
source("analysis/dm01_matched_current_data.R")

# report numbers: 
matched_data %>% summary_factorlist(
      dependent = "exposure",
      explanatory = c("sex", "age", "ethnicity", "bmi", "imd", 
                      "long_covid_dx", "covid_positive","previous_covid_hosp",
                      "cov_c19_vaccine_number",
                      "cov_cancer",
                      "cov_mental_health",
                      "cov_asthma",
                      "cov_organ_transplant",
                      "cov_chronic_cardiac_disease",
                      "cov_chronic_liver_disease",
                      "cov_stroke_dementia",
                      "cov_other_neuro_diseases",
                      "cov_ra_sle_psoriasis",
                      "cov_asplenia",
                      "cov_hiv",
                      "cov_aplastic_anemia",
                      "cov_permanent_immune_suppress",
                      "cov_temporary_immune_suppress",
                      "gp_visit_m1",
                      "gp_visit_m2",
                      "gp_visit_m3",
                      "gp_visit_m4",
                      "gp_visit_m5",
                      "gp_visit_m6",
                      "gp_visit_m7",
                      "gp_visit_m8",
                      "gp_visit_m9",
                      "gp_visit_m10",
                      "gp_visit_m11",
                      "gp_visit_m12",
                      "hos_visit_m1",
                      "hos_visit_m2",
                      "hos_visit_m3",
                      "hos_visit_m4",
                      "hos_visit_m5",
                      "hos_visit_m6",
                      "hos_visit_m7",
                      "hos_visit_m8",
                      "hos_visit_m9",
                      "hos_visit_m10",
                      "hos_visit_m11",
                      "hos_visit_m12",
                      "ae_visit_m1",
                      "ae_visit_m2",
                      "ae_visit_m3",
                      "ae_visit_m4",
                      "ae_visit_m5",
                      "ae_visit_m6",
                      "ae_visit_m7",
                      "ae_visit_m8",
                      "ae_visit_m9",
                      "ae_visit_m10",
                      "ae_visit_m11",
                      "ae_visit_m12"
                      ),
      p = TRUE
) %>% write.csv(here("output", "matched_numbers_table.csv"), row.names = F)


